# Generated by Django 2.2.3 on 2019-08-21 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pari', '0002_auto_20190809_2253'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
