# Generated by Django 2.2.3 on 2019-08-21 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pari', '0003_auto_20190821_1329'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
